LibraryAutomationSystem/Models/BookLanguage.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace LibraryAutomationSystem.Models
{
    public class BookLanguage
    {
        public int BookLanguageId { get; set; }
        [Required]
        [RegularExpression("^[A-Z][A-Za-z]*$",ErrorMessage ="BookLanguage Name not in correct format")]
        public string BookLanguageName { get; set; }
    }
}

LibraryAutomationSystem/Controllers/BookLanguageController.cs
using LibraryAutomationSystem.BL;
using System.Collections.Generic;
using System.Web.Mvc;

namespace LibraryAutomationSystem.Controllers
{
    [Authorize(Roles = "admin,user")]
    public class BookLanguageController : Controller
    {
        IBookLanguageBL bookLanguageBL;
        public BookLanguageController()
        {
            bookLanguageBL = new BookLanguageBL();//Creates the object for the BookLanguage Bl by IBookLanguageBL reference variable
        }
        // GET: BookLanguage
        [HttpGet]
        [ActionName("Create_BookLanguage")]
        [Authorize(Roles = "admin")]
        public ActionResult Create_BookLanguage_Get()//Get request of CreateBookLanguage
        {
            return View();
        }
        [ActionName("Create_BookLanguage")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create_BookLanguage_Post(Models.BookLanguageModel bookLanguage)//Add the BookLanguage 
        {
            if (ModelState.IsValid)
            {
                Entity.BookLanguage addLanguage = AutoMapper.Mapper.Map<Models.BookLanguageModel, LibraryAutomationSystem.Entity.BookLanguage>(bookLanguage);
                if (bookLanguageBL.AddBookLanguage(addLanguage) >= 1)
                    return RedirectToAction("View_BookLanguage");
                return View();
            }
            return View();
        }
        [HttpGet]
        [Authorize(Roles = "admin,user")]
        public ActionResult View_BookLanguage()//View the BookLanguage
        {
            IEnumerable<Entity.BookLanguage> languagelist = bookLanguageBL.GetBookLanguage();
            return View(languagelist);
        }
        [HttpGet]
        [Authorize(Roles = "admin")]
        public ActionResult Edit_Book_Language(int bookLanguageId)//Edit the book language by its Id
        {
            Entity.BookLanguage language = bookLanguageBL.FindBookLanguageById(bookLanguageId);//Get the Book Language Entity by Its Id
            Models.EditLanguageModel edit_language = AutoMapper.Mapper.Map<Entity.BookLanguage, Models.EditLanguageModel>(language);//Map the Entity to Model and Edit the Changes
            return View(edit_language);
        }
        [HttpPost]
        [ActionName("Edit_Book_Language")]
        public ActionResult Update_Book_Language(Models.EditLanguageModel editLanguage)//Update the Book 
        {
            if (ModelState.IsValid)
            {
                Entity.BookLanguage bookLanguage = AutoMapper.Mapper.Map<Models.EditLanguageModel, Entity.BookLanguage>(editLanguage);//Map the Model details to the Entity by Automapper
                if (bookLanguageBL.UpdateBookLanguage(bookLanguage) >= 1)
                    return RedirectToAction("View_BookLanguage");
            }
            return View(editLanguage);//Modelstate is false return to Edit Book
        }
        [HttpGet]
        public ActionResult Delete_Book_Language(int bookLanguageId)//Delete BookLanguage By Id
        {
            int a = bookLanguageBL.DeleteBookLanguage(bookLanguageId);
            return RedirectToAction("View_BookLanguage");

        }
    }
}

LibraryAutomationSystem/Views/BookLanguage/Create_BookLanguage.cshtml
@model LibraryAutomationSystem.Models.BookLanguageModel

@{
    ViewBag.Title = "Create_BookLanguage";
}

<h2 class="Heading">Create&mdash;BookLanguage</h2>

@using (Html.BeginForm("Create_BookLanguage", "BookLanguage", FormMethod.Post))
{
    <div class="AddLanguagecontainer row container">
        <div>
            @Html.DisplayNameFor(Model => Model.BookLanguageName)
            @Html.TextBoxFor(Model => Model.BookLanguageName, new { maxlength = 15, autocomplete = "off",@class="form-control" })
            @Html.ValidationMessageFor(Model => Model.BookLanguageName, "", new { @class = "error" })
        </div>
        <div>
            @Html.AntiForgeryToken()
            <input type="submit" class="link btn" />
            <input type="button" class="link btn"  value="Cancel" onclick='window.location="@Url.Action("View_BookLanguage","BookLanguage")";' />
        </div>
    </div>
}

LibraryAutomationSystem/Views/BookLanguage/Edit_Book_Language.cshtml
@model LibraryAutomationSystem.Models.EditLanguageModel

@{
    ViewBag.Title = "Edit_Book_Language";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<h2 class="Heading">Edit Book&mdash;Language</h2>
@using (Html.BeginForm("Edit_Book_Language", "BookLanguage", FormMethod.Post))
{
<div class="EditLanguageContainer row container">
    @Html.HiddenFor(Model => Model.BookLanguageId)
    <div>
        @Html.DisplayNameFor(Model => Model.BookLanguageName)
        @Html.TextBoxFor(Model => Model.BookLanguageName, new { maxlength = 25,@class="form-control" })
        @Html.ValidationMessageFor(Model => Model.BookLanguageName, "", new { @class = "error" })
    </div>
    <div>
        <input type="submit" value="update" class="btn link"/>
        <input type="button" value="Cancel" class="btn link"  onclick='window.location="@Url.Action("View_BookLanguage","BookLanguage")";' />
    </div>
</div>
}

LibraryAutomationSystem/Views/BookLanguage/View_BookLanguage.cshtml
@model IEnumerable<LibraryAutomationSystem.Entity.BookLanguage>

@{
    ViewBag.Title = "View_BookLanguage";
}
<link href="~/Content/Site.css" rel="stylesheet" />
<script src="~/Content/Library.js"></script>
<div class="row">
    <h2 class="Heading">View Book&mdash;Language</h2>
    <div class="Language">
        @Html.ActionLink("Add Language", "Create_BookLanguage", "BookLanguage", new { @class = "link btn" })
        <table>
            <tr>
                <th>
                    Book Language
                </th>
                <th>
                    Actions
                </th>
            </tr>
            @foreach (LibraryAutomationSystem.Entity.BookLanguage items in Model)
            {@Html.HiddenFor(Model => items.BookLanguageId)
                <tr>
                    <td>
                        @items.BookLanguageName
                    </td>

                    <td>
                        @Html.ActionLink("Edit", "Edit_Book_Language", new { bookLanguageId = items.BookLanguageId }, new { @class = "link btn" })
                        @Html.ActionLink("Delete", "Delete_Book_Language", new { bookLanguageId = items.BookLanguageId }, new { onclick = "return delete_Function('" + items.BookLanguageName + "');", @class = "link btn" })
                    </td>
                </tr>
            }

        </table>
    </div>
</div>